### PR TITLE
Add auto testing to Github actions

### PR DESCRIPTION
**Pull request by jgsheppa**
Created .yml file for auto testing.

Also deleted `disabled` from join party.

### CODE REVIEW

**Comment by jacten** [comment]
In theory this is a cool addition. But I think there is an issue with how our tests are set-up that causes issues. Perhaps something to do with how we run them synchronously. Perhaps something to with interacting with atlasDB from Github. Maybe need to whitelist github or something like that? Either way I can't really feel good merging this in until the tests run and pass. 

I just re-ran the test (which failed before) and after 13 minutes it is still running so something isn't right there.

**Comment by jacten** [comment]
Also, I see you added the github secret for a mongo-uri. Which mongo-uri is that account pointing to? Do we have a separate dev one or is that a personal one you created? 

Also how does this interact with the other github actions on the release branch?

**Comment by jgsheppa** [comment]
Yeah, I tried to get this going, but I got the sense that it wouldn't work. Maybe I'll just delete this commit?

**Comment by jacten** [comment]
> Yeah, I tried to get this going, but I got the sense that it wouldn't work. Maybe I'll just delete this commit?

If you want to close this PR that is fine. We can revisit this later. Still good practice for you.

**Pull request closed without merging**
